# Generated by Django 3.0.3 on 2020-02-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagem', models.IntegerField()),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Amostra')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Taxonomia')),
            ],
        ),
    ]
